### PR TITLE
Dolev/config ignored mails

### PR DESCRIPTION
**Pull request by dolby360**
# Pull Request

## Description
Add option to ignore list of emails and users on signoff stage 

> Describe what you did and why.

**Related issue (if any):** fixes #*58*

## Checklist

- [V] I have followed this repository's contributing guidelines.
- [V] I have used the conventional commits specification for my commit messages.
- [V] I have signed my commits.
- [V] I will adhere to the project's code of conduct.

## Additional information

> Anything else?
>

### CODE REVIEW

**Comment by dolby360** [comment]
I'll take a look tomorrow why it failed

**Comment by dolby360** [comment]
@TomerFi The only issue left is a known issue.

**Comment by TomerFi** [comment]
@dolby360 
Both this and your previous contributions were a part of the new release [1.2.0](https://github.com/TomerFi/auto-me-bot/releases/tag/1.2.0).

Thank you very much!

**Comment by dolby360** [comment]
Thank you.
It's a pleasure working with you. Be ready for many more;)

בתאריך יום ד׳, 17 באוג׳ 2022, 17:42, מאת Tomer Figenblat ‏<
***@***.***>:

**Pull request merged**
