### PR TITLE
Ignore bots signoff check

### PR DESCRIPTION
**Pull request by dolby360**
in case a branch contains bot commits then these commits will not be checked.
this code assumes that the email address of all bots contains [bot].

Signed-off-by: dolby360 <dolevben054@gmail.com>

# Pull Request

## Description

> Describe what you did and why.

**Related issue (if any):** fixes #*47*

## Checklist

- [V] I have followed this repository's contributing guidelines.
- [V] I have used the conventional commits specification for my commit messages.
- [V] I have signed my commits.
- [V] I will adhere to the project's code of conduct.

## Additional information

> Anything else?
>

### CODE REVIEW

**Review by TomerFi — CHANGES_REQUESTED** [review]
@dolby360 
To fix the failing test and CI:

---

[here](https://github.com/dolby360/auto-me-bot/blob/ca844ee66216874657ba92e09d2a5bc9fef7cfb3/tests/handlers/pr-signed-commits.test.js#L352):

```javascript
.withArgs(fakeUnknownEmail, sinon.match.func)
```
Change `fakeUnknownEmail` to `fakeBotEmail`.

---

[Here](https://github.com/dolby360/auto-me-bot/blob/dolev/ignore_bots_signoff_check/tests/handlers/pr-signed-commits.test.js#L356):

```javascript
listCommitsStub.resolves({data: [commitSignedByUnknown]});
```
Change `commitSignedByUnknown` to `commitUnsignedBot`.

---

The commit message type is `feat!`, amend it to `feat`.

**Comment by TomerFi** [comment]
@dolby360 
Thank you very much, I will be merging this by tomorrow.

I just want to take the opportunity of this PR and fix the CI issue,
the "Report test results" step fails because of missing permission for forks,
and I can verify a fix with your PR open, so I want to play with it a bit if you don't mind.

Can you please verify the `Allow edits by maintainers.` checkbox is ticked so I can push a fix here?

**Comment by dolby360** [comment]
> Can you please verify the `Allow edits by maintainers.` checkbox is ticked so I can push a fix here?

Already on. Please take your time there's no rush.

**Comment by TomerFi** [comment]
> Already on. Please take your time there's no rush.

Weird... I try pushing yesterday, and I got a permissions error, I figured it's the maintainers' thing, but I didn't look anymore into it.

I am looking into it now.

**Pull request merged**
