### PR TITLE
feat: passing only relevant configurations to handler

### PR DESCRIPTION
**Pull request by dolby360**
Signed-off-by: dolby360 <dolevben054@gmail.com>

## Description
Fixing [issue 46](https://github.com/TomerFi/auto-me-bot/issues/46)
**Related issue (if any):** fixes #*46*

## Checklist

- [v] I have followed this repository's contributing guidelines.
- [v] I have used the conventional commits specification for my commit messages.
- [v] I have signed my commits.
- [v] I will adhere to the project's code of conduct.

## Additional information

> Anything else?
>

### CODE REVIEW

**Comment by dolby360** [comment]
@TomerFi Is this a real failure? 
https://github.com/TomerFi/auto-me-bot/runs/7761677273?check_suite_focus=true#step:7:26
It seems like it wasn't able to generate some artifacts.

**Review by TomerFi — APPROVED** [review]

**Comment by TomerFi** [comment]
@dolby360 thank you very much!
you can ignore the CI error - it's missing the content: write perms - I'll fix it on the main branch.

merging this!

**Comment by TomerFi** [comment]
@dolby360 
we may need to revert this, this CI workflow was faulty and tests fail for this change.
I'm looking into it.

https://github.com/TomerFi/auto-me-bot/runs/7764413988?check_suite_focus=true

**Comment by TomerFi** [comment]
Fixed here https://github.com/TomerFi/auto-me-bot/pull/57.
I hope I was also able to fix the workflow issue that checked out the wrong sources.
We'll see in the next forked PR.
:-)

**Pull request merged**
